name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [^9.5, ^10.0, dev-master]
        php: ['7.2', '7.3']

    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Lint PHP
        run: .Build/bin/phplint

      - name: Unit Tests
        run: .Build/bin/phpunit --colors -c Tests/Build/UnitTests.xml
